- Contributing.md
- README.md
- docs/guides/custom.md
- docs/install.md
- everyvoice/cli.py
- everyvoice/model/e2e/model.py
- everyvoice/preprocessor/preprocessor.py
- everyvoice/wizard/basic.py
- mkdocs.yml
- requirements.txt
- setup.py
Reflect the new location of the EveryVoice repo and its submodules.
Fixes #488
> docs: rename links to GitHub repos to the EveryVoiceTTS space

- everyvoice/tests/stubs.py
- everyvoice/tests/test_wizard.py
Improve the effective coverage when using `monkey_run_tour()` by patching deeper at each step when possible, instead of just patching `step.prompt()` itself by default.
Includes refactorings to facilitate making that change.
Standard code review
low
nothing but!
run the unit tests
high
no
none
> Wizard test improvements

- everyvoice/text/text_processor.py
Fix some mypy errors
sanity check
normal
just what was there
run `mypy everyvoice` before and after and see fewer errors, run the test suite and see it pass.
high
no
https://github.com/EveryVoiceTTS/FastSpeech2_lightning/pull/84
> Dev.ej/fix some mypy errors

- everyvoice/tests/test_wizard.py
- everyvoice/wizard/__init__.py
- everyvoice/wizard/basic.py
- everyvoice/wizard/dataset.py
Fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/470.
This PR fixes multilingual/multispeaker config setting for new projects.
Fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/470.
1. Check the correctness of the commit history. The branch for this PR has been rebased on top of the PR https://github.com/EveryVoiceTTS/EveryVoice/pull/509 branch. I wonder if I should still request merge into main or into a different branch.
2. Feedback on wording of new prompts in the wizard is greatly appreciated.
3. Take a close look at test_wizard.py/WizardTest/test_running_out_of_columns. It has steps added to make the test case complete.  I though that it would be better if the test would go through all steps and compare output with the expected one. Is it appropriate for this test or …
> fix(wizard): fixes multilingual/multispeaker config setting in new projects

- everyvoice/cli.py
- everyvoice/demo/app.py
Fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/477
Launching the demo, the introduced changes provide an option to hide some of the languages and speakers the model was trained with.
Fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/477
Feedback on wording of messages for invalid input.
Low.
No new tests.
Run demo providing optional -l and -s arguments.
Medium.
No.
Uses and updates the changes implemented in https://github.com/EveryVoiceTTS/EveryVoice/pull/511. This PR should be merged after PR 511.
> feat(demo): adds an option to specify languages and speakers available in demo

- everyvoice/cli.py
- everyvoice/demo/app.py
Fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/476
Locks fields in the demo which do not contain options to choose from. 
Fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/476.
It's possible to hide these fields when they are not interactive, but I think it's better to still display them to indicate speaker/language used for model training. What is your opinion?
Low.
No tests are added.
Run demo with multilingual/multispeaker and monolingual/monospeaker models. Check that fields are locked when its appropriate.
High.
No.
No.
> fix(demo): locks dropdown lists when only one option is available

- everyvoice/cli.py
- everyvoice/preprocessor/preprocessor.py
- everyvoice/tests/test_preprocessing.py
Incorporate TorchSquim metrics into EveryVoice data checking
Sanity check. Review functionality
low
None, we should add some tests to check that the data checker is working basically
`everyvoice check-data <path_to_config> --heavy-objective-evaluation`
medium
No
> Dev.ap/torch squim

- everyvoice/config/text_config.py
- everyvoice/tests/data/relative/config/everyvoice-shared-text.yaml
- everyvoice/tests/test_text.py
- everyvoice/tests/test_wizard.py
- everyvoice/wizard/dataset.py
Add the validation and punctuation handling discussed in https://github.com/EveryVoiceTTS/EveryVoice/issues/484
#450 and #484
confirmation this is the strategy we want to use
medium
yes
try running it on an existing config with punctuation symbols in your character list
medium
yes, should trigger a version change as it is breaking
> Fix punctuation handling

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
Add [pre-commit.ci](https://pre-commit.ci/) as a workflow.
fixes: #117
Approval to merge.
medium
None
On GitHub, run it as a github action.
Will run on each pull request.
fair
No
None
> feat: added pre-commit.ci

- requirements.txt
Bump nltk to clear CVE report, although in this case it probably didn't really matter, I don't think we're using the vulnerable code in NLTK.
Fixes https://github.com/EveryVoiceTTS/EveryVoice/security/dependabot/7
low
already covered
> fix(deps): bump nltk to 3.9.1 to fix CVE

- everyvoice/cli.py
- everyvoice/evaluation.py
- everyvoice/run_tests.py
- everyvoice/tests/test_cli.py
- everyvoice/tests/test_evaluation.py
Allow EveryVoice to do some basic evaluation by running `everyvoice evaluate` on either a single wav or directory of wavs.
Try it out, is the API intuitive?
medium
A unit test of the evaluation is included, other test ideas are welcome.
run `everyvoice evaluate --help` and then follow the instructions on some audio that you have.
medium
minor
N/A
> Basic Objective evaluation

- .github/workflows/test.yml
Fix the pre-commit CI failures
Fixes #555
rubber stamping
high, since this causes CI to fail on PRs touching submodules
high
> fix(ci): only run pre-commit on files in the main EV repo

- everyvoice/cli.py
It always takes me too long to figure out which model I need to provide when the help says I need a text-to-spec model.
This PR clarifies that.
My lack of intuition for why "spec" and "features" are synonyms... I'm probably not the only one!
low
n/a
run 
- `everyvoice demo -h`
- `everyvoice synthesize from-text -h`
and see the model path description clarified
high, but there is one question mark: are all text-to-spec models feature prediction models? If not, and there are other kinds, I would write `(e.g., feature prediction)` instead of `(i.e., feature prediction)`.
no
https://github.com/EveryVoiceTTS/FastSpeech2_lightning/pull/89
> Dev.ej/clarify text to spec

- everyvoice/wizard/__init__.py
quick fix to remove accidentally committed debugging code
high
> fix: remove debugging code accidentally committed

- everyvoice/base_cli/helpers.py
- everyvoice/demo/app.py
- everyvoice/tests/test_model.py
- everyvoice/utils/__init__.py
Fix #263 by providing a friendlier message when the user provide the wrong checkpoint.
#263 
Merge approval
high
Yes
```sh
python -m unittest \
everyvoice.tests.test_model.TestLoadingModel.test_model_is_not_a_feature_prediction \
everyvoice.tests.test_model.TestLoadingModel.test_model_is_not_a_vocoder
```
```sh
everyvoice synthesize from-text \
logs_and_checkpoints/VocoderExperiment/base/checkpoints/last.ckpt \
-t "this is a test" \
--vocoder-path  ~/u/EveryVoice/vocoder_paths/generator_universal.pth.tar
```
```sh
everyvoice synthesize from-text \
logs_and_checkpoints/FeaturePredictionExperiment/base/checkpoints/last.ckpt \
-t "this is a test" \
--vocoder-path logs_and_checkpoints/FeaturePredictionExperiment/base/checkpoints/last.ckpt
```
```sh
python -m …
```
> Handling wrong checkpoint

- everyvoice/cli.py
- everyvoice/utils/__init__.py
- requirements.txt
When you run many EveryVoice commands, there's no feedback on screen telling you the command is doing something, and isn't just hanging. With this PR, expensive imports get a spinner that looks like `⠼ Loading... (0:00:10.61)` while loading, and `Done Loading (0:00:21.57)` when done loading.
If the process is run interactively, update is every 9th of a second, but if it's going to a log it's only every 2 seconds, to avoid filling up the log file with garbage.
My impatience waiting for stuff to actually happen when I run EV commands.
How you like it.
low
no, we don't have the framework to test most of these yet, athough some of these commands will be covered by existing unit testing, and I don't feel the need to add assertions, all that matters is that things continue to run as they used …
> Add a yaspin spinner on CLI commands while expensive imports are happening

- .github/workflows/docs.yml
- .github/workflows/publish.yaml
- .github/workflows/test.yml
- README.md
Make the licensing options clear for the alternative places you can get `conda` from.
rubber-stamping
medium
> docs: suggest getting conda from miniforge

- docs/guides/custom.md
- docs/guides/finetune.md
- everyvoice/cli.py
In writing the documentation for `everyvoice segment` I realized that we didn't actually have an easy way of extracting the text/audio intervals from the textgrid into the format needed by Everyvoice. This PR adds that feature and also updates the documentation.
https://github.com/EveryVoiceTTS/EveryVoice/issues/543
https://github.com/EveryVoiceTTS/EveryVoice/issues/544
Sanity. Suggest any changes to the CLI method names or documentation.
medium
For this to work you need a plain text transcript and some corresponding audio. You can then run the segmenter: everyvoice segment align path_to_text.txt path_to_audio.wav. You can then install [Praat](https://www.fon.hum.uva.nl/praat/) and use it to inspect the .TextGrid file that was generated, and adjust any alignments as necessary. Once you …
> Extract alignment from textgrid

- everyvoice/cli.py
- everyvoice/tests/test_cli.py
- everyvoice/tests/test_wizard.py
add `--version` and `--diagnostic` top-level options to EV.
Fixes #549
beta
ues
Run
`everyvoice --version` and `everyvoice --diagnostic`
high
> feat: add --version and --diagnostic top-level options

- pyproject.toml
Fix https://github.com/EveryVoiceTTS/EveryVoice/security/dependabot/9
setuptools vulnerable to Command Injection via package URL
merge approval
medium
None
None
????
No
None
> feat: updated setuptools vulnerable to Command Injection via package URL

- everyvoice/.schema/everyvoice-aligner-0.2.json
- everyvoice/.schema/everyvoice-spec-to-wav-0.2.json
- everyvoice/.schema/everyvoice-text-to-spec-0.2.json
- everyvoice/.schema/everyvoice-text-to-wav-0.2.json
- everyvoice/_version.py
Fix missing default VERSION reported by `mypy`.
https://github.com/EveryVoiceTTS/EveryVoice/issues/581
merge approval
high
no
`pre-commit run --all`
good
no
None
> feat: fixing mypy complaint about mypy

- everyvoice/.schema/everyvoice-aligner-0.2.json
- everyvoice/.schema/everyvoice-spec-to-wav-0.2.json
- everyvoice/.schema/everyvoice-text-to-spec-0.2.json
- everyvoice/.schema/everyvoice-text-to-wav-0.2.json
- everyvoice/_version.py
- everyvoice/model/e2e/cli.py
- everyvoice/model/e2e/dataset.py
- everyvoice/tests/test_cli.py
- everyvoice/tests/test_configs.py
- everyvoice/tests/test_preprocessing.py
- everyvoice/tests/test_wizard.py
Will investigating #581 , I ran `pre-commit run --all` and `flake8` made some changes to some files
Update some files changed by `flake8`.
merge approval
low
None
`pre-commit run --all`
good
No
depends on: https://github.com/EveryVoiceTTS/EveryVoice/pull/583
> feat: auto fixing from black

- everyvoice/base_cli/checkpoint.py
- everyvoice/base_cli/interfaces.py
- everyvoice/cli.py
- everyvoice/tests/test_cli.py
Stop using deprecated `autocompletion` before it is actually removed from the libraries we use (click and typer)
When you run `python -m unittest everyvoice.tests.test_cli`, you get this warning repeated several times:
> /gpfs/fs3c/nrc/ict/portage/u/joa125/miniforge3/envs/ev-py310/lib/python3.10/site-packages/typer/core.py:454: DeprecationWarning: 'autocompletion' is renamed to 'shell_complete'. The old name is deprecated and will be removed in Click 8.1. See the docs about 'Parameter' for information about new behavior.
_typer_param_setup_autocompletion_compat(self, autocompletion=autocompletion)
This PR makes the warning go away, and make our code base more future proof.
sanity checking
beta
it affects interactive use, so I'm not sure how I could test it.
Make sure `everyvoice …
> Replace deprecated autocompletion by shell_complete in all modules

- everyvoice/cli.py
See https://github.com/EveryVoiceTTS/HiFiGAN_iSTFT_lightning/pull/43
> Dev.ej/refactor hfg

- everyvoice/base_cli/interfaces.py
- everyvoice/tests/test_cli.py
- everyvoice/utils/__init__.py
- pyproject.toml
See https://github.com/EveryVoiceTTS/wav2vec2aligner/pull/16
Plus slow down the yaspin spinner update speed to reduce annoying flicker
> Dev.ej/fix typer

- everyvoice/demo/app.py
- pyproject.toml
The demo is broken! This fixes it by passing the expected format of the wav samples to gradio. I also bumped gradio as discussed.
Test out the demo to make sure, but mostly sanity.
high
high
> Dev.ap/fix gradio

- everyvoice/cli.py
- everyvoice/demo/app.py
- everyvoice/tests/test_cli.py
Apply my suggestions to #617, make the code DRYer, fix the Spec download format, etc.
regular code review, testing
same as #617
not yet, but as AP said that's work in progress coming soonish
Spin up the demo and try to synthesize with every file format.
Read through at the output of `everyvoice demo -h`
Pass various combinations of valid and invalid values with -O add see what happens.
high
This and #617 bring a new feature, so that would logically warrant a minor bump, but I think we've already got other such features. Soon I think?
https://github.com/EveryVoiceTTS/FastSpeech2_lightning/pull/106
> Refactor and fix the demo format code

- everyvoice/base_cli/checkpoint.py
- everyvoice/base_cli/helpers.py
- everyvoice/dataloader/__init__.py
- everyvoice/demo/app.py
- everyvoice/model/e2e/dataset.py
- everyvoice/preprocessor/preprocessor.py
- everyvoice/tests/test_model.py
- everyvoice/tests/test_preprocessing.py
Prepare EV to be compatible with pytorch 2.4.1 and future, when the default `weights_only=False` eventually will get changed to `weights_only=True`.
https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models documents how one should not load data files received from a third party with `weights_only=False`, so I figure it's important to at least change how we load our checkpoints.
To create this PR, I set `weigths_only=True` on every single `torch.load()` call in EV, and ran stuff (using unit testing and the wip regress branch): it turns out our checkpoints and most of our uses are OK with only "tensors, primitive types, dictionaries". The only exception I found is prepared datasets, and I think it's reasonable to use weights in that case since those files will be created …
> fix: make torch.load safer with weights_only=True everywhere possible

- everyvoice/tests/test_cli.py
- pyproject.toml
See
https://github.com/EveryVoiceTTS/DeepForcedAligner/pull/33
https://github.com/EveryVoiceTTS/wav2vec2aligner/pull/18
https://github.com/EveryVoiceTTS/FastSpeech2_lightning/pull/108
https://github.com/EveryVoiceTTS/HiFiGAN_iSTFT_lightning/pull/48
> build: convert setup.py to pyproject.toml in all submodules

- .github/workflows/docs.yml
- .github/workflows/publish.yaml
- docs/guides/schemas.md
- docs/requirements.txt
- mkdocs.yml
- pyproject.toml
Several related things:
- https://docs.everyvoice.ca/stable/guides/schemas/ is a bit confusing, because we don't talk about schemas in general, we just jump into installing them in vim. Let's have an intro to this page.
- To test the above, I naturally did `pip install -e .[docs]`, as it should be, but it didn't work. Now it does.
- I find it unfriendly when navigation is only possible from the TOC, so I added to footer with previous/next links.
normal review
low
n/a
```
pip install -e .[docs]
mkdocs serve
```
and then review the update page at http://127.0.0.1:8000/guides/schemas/
high
no
no
> mention schemas for vscode before delving into vim, and modernize how docs deps are installed

- everyvoice/tests/test_wizard.py
When you can't download stuff from the web, you get long warnings, that can be safely be ignored. Hide them.
rubber stamping
low
it's only tests
Run unit tests in a cluster job with the proxies not enabled.
high
no
https://github.com/EveryVoiceTTS/FastSpeech2_lightning/pull/111
https://github.com/EveryVoiceTTS/wav2vec2aligner/pull/20
> Silence misleading error messages when running tests on the cluster and there is no Internet.

- everyvoice/demo/app.py
- everyvoice/tests/regression/.gitignore
- everyvoice/tests/regression/README.md
- everyvoice/tests/regression/combine-coverage.sh
- everyvoice/tests/regression/go-gpsc5.sh
- everyvoice/tests/regression/go-gpscc.sh
- everyvoice/tests/regression/go-trixie.sh
- everyvoice/tests/regression/go.sh
- everyvoice/tests/regression/prep-datasets.sh
- everyvoice/tests/regression/regression-test.sh
- everyvoice/tests/regression/run-demo-app-lj-full.sh
- everyvoice/tests/regression/run-demo-app-mix.sh
- everyvoice/tests/regression/test-demo-app-lj-full.py
- everyvoice/tests/regression/test-demo-app-mix.py
- everyvoice/tests/regression/wait-for-demo-app.py
- everyvoice/tests/regression/wizard-resume-mix
- everyvoice/tests/test_cli.py
- pyproject.toml
The overall goal is to improve the regression test suite in various ways.
1) improve the coverage reports
2) use playwright to exercise the demo in testing
3) factor out how to submit regression on different clusters
4) add a mix-corpus test case in the regression suite
I know it would be better to splice this is 2 or 3 PRs, but I didn't leave myself enough time to do that before Jordan arrives and I'm hoping he'll work on top of this branch, so I'm submitting it now like this.
Flag egregious issues only. This is still work in progress anyway, but I think it's in a state that's already worth merging, and we'll keep improving it in future PRs.
high
it's all just testing
run the regression suites on a cluster
high that it's ok to merge now, but I know we'll keep improving on this.
no
no
> Dev.ej/regress rebooted

- everyvoice/tests/regression/prep-datasets.sh
Regression test script prep-datasets.sh was edited to produce regression testing datasets:
regress-\<dataset\>-\<duration\> subsets at 15 mins, 60 mins, 180 mins and full dataset
Issue #655
Please run the regression tests and confirm they work properly/pass.
medium
N/A no python code in this PR
Run the regression tests. Manually check the new datasets created.
This code cannot be merged without some git history revision due to it being reliant on #648 and #654 
Minor
PR #648 
PR #654
> Dev.jl/regress subsample

- .github/workflows/docs.yml
- docs/reference/configuration.md
Run the docs workflow only when we merge changes to main that can affect the docs.
Specifically:
- changes to docs.yaml
- changes to docs/**
- changes to everyvoice/config/text_config.py because some of that file's contents is embedded into https://docs.everyvoice.ca/dev/reference/configuration/
Will suppress unnecessary commits to the gh-pages branch.
regular validation
low
no, but I tested manually by gutting the action to do nothing, and pushed changes that should and should not trigger the action, and confirmed it behaved as expected.
high
no
none
> ci: only deploy docs if relevant files have changed

- LICENSE
- everyvoice/.schema/everyvoice-shared-text-0.4.json
- everyvoice/.schema/everyvoice-text-to-spec-0.4.json
- everyvoice/.schema/everyvoice-text-to-wav-0.4.json
- everyvoice/base_cli/helpers.py
- everyvoice/base_cli/interfaces.py
- everyvoice/cli.py
- everyvoice/config/text_config.py
- everyvoice/demo/app.py
- everyvoice/run_tests.py
- everyvoice/tests/data/relative/config/everyvoice-shared-text.yaml
- everyvoice/tests/data/text.txt
- everyvoice/tests/g2p_engines/__init__.py
- everyvoice/tests/test_cli.py
- everyvoice/tests/test_text.py
- everyvoice/text/textsplit.py
Allow chunking of texts when synthesizing audio with FastSpeech2, to better match longer audio inputs with training data.
More changes will be added to improve this feature, but this PR is for the **_minimum viable product_**. For example, text splitting is only available for output types wav and spec (a warning occurs when synthesizing another output type). Support for the other file outputs will come later.
This is a combination of 3 separate issues:
Fixes #691
Fixes #658
Solves 1/4 of #673 
Any
high: I would like this to be merged sooner than later to prevent this large branch from becoming stale.
Yes
- Perform all kinds of different text to wav synthesis (using demo, from filelist, from -t, using -c to turn splitting on and off).
- Also try to synthesize with --output-type ≠ wav and …
> Text Splitting Main Branch PR

- everyvoice/config/text_config.py
- everyvoice/tests/test_configs.py
- everyvoice/wizard/basic.py
- everyvoice/wizard/dataset.py
- everyvoice/wizard/prompts.py
- everyvoice/wizard/tour.py
- everyvoice/wizard/utils.py
The PR for custom g2p questions involved a lot of stuff, and is going to be a mess to review.
The help alleviate the situation, I have created this PR which is only refactorings of the wizard, that I did for the purpose of the custom g2p improvements, but which can stand alone by themselves and therefore can be reviewed separately.
general review and sanity checking.
At times, you will wonder "why bother?" for some changes. By default, assume "because it supported writing the custom g2p questions."
normal
This code was already well covered by tests. The next PR will have lots of new tests, but not this one.
I think if CI passes, it's all good, to be honest. But you can also run the Wizard and see that there are no surprises.
high
no
This PR prepares the way for #711
> Wizard refactorings in preparation for the custom g2p enhancements

- everyvoice/run_tests.py
- everyvoice/tests/test_configs.py
- everyvoice/tests/test_custom_g2p.py
- everyvoice/tests/test_text.py
- everyvoice/tests/test_wizard.py
There are a growing number of tests related to custom g2p, that touch various parts of the code base but are all related.
Also, test_wizard is getting unwieldingly large.
So I propose to group all the custom g2p tests in one place.
This PR does that, and only that, it changes no tests, it only moves them around.
I want to isolate this to make review manageable, because combining this with any other PR will make that have a huge diff where it won't be clear what's new and what's just moved.
Sanity checking
Just exercise unit tests before and after, and see the same number of tests run and passed.
high
no
Builds on #711
> Group all custom g2p tests in one new test file

- docs/guides/custom.md
Fix broken link in docs
Fixes #681
Does it make sense?
trivial
n/a
100%
n/a
> docs: updated instructions on how to download vocoder

- .github/workflows/test.yml
1) The quite some time now, the `licensecheck` call in the workflow has not been working, and thus our automated due diligence has been disabled. This PR primarily fixes that.
~2) While working on the PR, it's annoying how pre-commit and licensecheck, with no dependencies on the EV test suite, delay it and/or are delayed by it. So I refactored the workflow into three independent jobs which can start at the same time and provide their independent results faster.~ UPDATE: combining these changes makes review too hard, splitting this into a separate PR. #750
broken license check
medium
it's all just tests
look at the CI runs for this PR
high:
- I have push commits that deliberately make license checking fail and see them fail at the right place
- I will make sure a pre-commit failure has the …
> Dev.ej/repair licensecheck
