EveryVoiceTTS/EveryVoice

requirements.txt

Make CI pass again while we remain incompatible with Pydantic 2.8.0
Workaround for #498, but not a fix.
rubber-stamping -- CI passing is all the feedback I need.
high
n/a
see #498
high
no
none

fix(deps): lock pydantic <2.8 until we fix bug #498

---

everyvoice/_version.py

Preparing to publish 0.1.0a3 to pypi
TODO:
```
git push origin origin/dev.ej/v0.1.0a3:main
git tag -a -m v0.1.0a3 v0.1.0a3 origin/dev.ej/v0.1.0a3
git push origin v0.1.0a3
```

chore: publish 0.1.0a3 with pydantic dependency fix

---

everyvoice/tests/test_wizard.py
everyvoice/wizard/dataset.py

Although the bug majorly affected festival data only, updating 'text' keyword is done in general way now. So, if sv-like data is read into dict, it should work well. Fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/496
Makes the wizard work for festival data format.
Fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/496
Check if it works.
Medium. Blocks testing of the developed solution for the issue https://github.com/EveryVoiceTTS/EveryVoice/issues/470.
Added a new complete-tour wizard test for data in the festival format.
Try to create a new project with a filelist in a festival format.
High. Quite a minor fix.
Probably, yes. Depends on how important the ability of work with data in the festival format is.
No

fix(wizard): fixes non-updating keyword of text in data dictionary

---

everyvoice/tests/test_wizard.py
everyvoice/wizard/dataset.py

reload_filelist_data_as_dict() can't have to reload a festival file, so replace the unreachable code by an assertion.
Also bump coverage by using the null_patch() and HasLanguage and HasSpeaker when testing festival, so that we run the prompt() function and let it detect that the format is festival.
Just a minor tweak
nudges coverage up
just review code
low
mostly just modifies tests
run the test suite and see coverage change
high
no
minor improvement on #497

refactor: remove unreachable code and bump coverage

---

everyvoice/tests/test_wizard.py

Children steps created at the tour initialization can be reached now. Fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/508
Modifies the condition for the children steps recursion in `monkey_run_tour()`, removes unreasonable blocking.
Fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/508
Are there any cases when we don't want to run children steps of a step which has a number of children steps reduced after its run?
Medium. Blocks testing of the developed solution for the issue https://github.com/EveryVoiceTTS/EveryVoice/issues/470.
Adds no new tests.
Run wizard testing and check if this PR breaks anything. 
Medium. Don't know why this condition was initially added.
No. Fix of a bug in tests which hasn't revealed itself so far.
No, so far.

fix(tests): removes blocking of reaching children steps

---

everyvoice/tests/test_wizard.py
everyvoice/wizard/dataset.py

Give a better prompt to the user when an empty file list is given.
Fixes #333 
For now, if the user gives an empty list, we will give `ERROR: File ({filelist_path} is empty. Please double check.` and then let the program exit. It may be worthwhile to develop a new feature that allows the user to re-select the file. I'm open to insight on how to make this happen and we may handle it in another PR. Thanks!
Normal
Yes
Run `everyvoice test cli` or iniitalize `everyvoice new-project` with an empty file list.
High
No

fix: better handling of empty filelist

---

everyvoice/config/text_config.py
everyvoice/model/e2e/config/__init__.py
everyvoice/tests/data/unit-test-case1.psv
everyvoice/tests/test_text.py
everyvoice/tests/test_wizard.py
everyvoice/utils/__init__.py
everyvoice/wizard/dataset.py

Whitespace collapsing wasn't being applied by the wizard, only the chosen cleaners. This changes that.
sanity, code check
medium
✅ 
medium-high
no
#515 and #516

fix: add whitespace collapsing and text stripping by default

---

.github/workflows/pre-commit.yml

#494 adds pre-commit hooks CI but trilom/file-changes-action is unmaintained and it is suggested to replace it with tj-actions/changed-files.
Merge approval
low
None
Look at github's action for `pre-commit-ci-lite` and noticed there is no longer
```
Run trilom/file-changes-action@v1.2.4
with:
output:  
githubToken: ***
fileOutput: json
env:
pythonLocation: /opt/hostedtoolcache/Python/3.10.14/x64
PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.10.14/x64/lib/pkgconfig
Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.10.14/x64
Python[2](https://github.com/EveryVoiceTTS/EveryVoice/actions/runs/10082383575/job/27876484800#step:5:2)_ROOT_DIR: /opt/hostedtoolcache/Python/[3](https://github.com/EveryVoiceTTS/EveryVoice/actions/runs/10082383575/job/27876484800#step:5:3).10.14/x6[4](https://github.com/ …
```

fix(ci): replaced trilom/file-changes-action with tj-actions/changed-files since it is not maintained

---

everyvoice/config/text_config.py
everyvoice/model/e2e/config/__init__.py
everyvoice/tests/data/relative/config/everyvoice-shared-text.yaml
everyvoice/tests/data/unit-test-case1.psv
everyvoice/tests/test_text.py
everyvoice/tests/test_wizard.py
everyvoice/utils/__init__.py
everyvoice/wizard/dataset.py

this allows for any processes that take place on the filelist list data (i.e. normalization) to be preserved
fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/504
Ensures that we are outputting a set of symbols without duplicates
#504 
sanity. code clarity
medium
tests updated
You could try re-running on your dataset to see how the config changes
medium
none. this isn't a breaking change. no version change needed really.

fix: change shape of filelist list data instead of re-reading it

---

everyvoice/config/text_config.py
everyvoice/tests/test_cli.py
everyvoice/tests/test_wizard.py
everyvoice/wizard/dataset.py
everyvoice/wizard/prompts.py

Multiple improvements and fixes to the new-project wizard.
Fix the problem where the wizard would include `''` in `test_characters` and thus make `everyvoice train text-to-spec` fail.
Fix the problem where the wizard crashes if you select no text transformations.
Make sure the URL for documentation of NFC normalization is fully legible even when your terminal is not super wide.
Other side improvements to the wizard at the same time.
regular review
High because at the moment, the wizard is broken, 
- adding `''` to `test_characters` in `config/everyvoice-shared-text.yaml`, which causes a failure when you run `everyvoice train text-to-spec`;
- crashing if you select no text transformations.
yup
run the wizard and see:
- the URL for NFC normalization is now fully on your screen (used to get …

multiple patches to the new-project wizard

---

everyvoice/demo/app.py
make-everyvoice-env

Make sure ffmpeg is installed, and error out for a clear message if not
two changes:
- `make-everyvoice-env` now just always installs ffmpeg
- `everyvoice demo` exits right away if ffmpeg is not found, since we know we'll crash when the user eventually clicks on `synthesize`
Fixed #527
general validation
beta
no, because we don't have any CI for `everyvoice demo` at the moment.
1) get yourself an environment where ffmpeg is not installed (`which ffmpeg` will return nothing) and run `everyvoice demo fp.ckpt vocoder.ckpt` and see it exit with clear instructions.
2) create a new environment with `make-everyvoice-env` and see that `which ffmpeg` is right in your conda env.
high
I tested this thoroughly, with ffmpeg not on my path, and with ffmpeg on my path but corrupted (and thus not …

Make sure ffmpeg is installed, and show a clear message if not

---

requirements.dev.txt
requirements.txt

also:
- bump matplotlib to the current version, already bundled with type hints
- declare numpy < 2 since torch < 2.4.1 requires it without declaring it
Allow g2p 2.1.0 with EveryVoice
low
CI test suites should do
high

chore: dependency maintenance to allow g2p 2.1

---

everyvoice/base_cli/helpers.py

Fix proper resuming of `text-to-spec` training.
The state at the end of the last epoch wasn't saved and resuming would be performed from the last saved checkpoint that was the last checkpoint used for validation.  This was producing staggered runs as shown in `tensorboard`.
#534 
merge approval
low
None
```sh
srun everyvoice train text-to-spec \
config/everyvoice-text-to-spec.yaml \
--config-args training.max_epochs=1 \
```
Check the state of the loops
```sh
python -c 'import torch; import json; m = torch.load("logs_and_checkpoints/FeaturePredictionExperiment/save_on_train_epoch_end/checkpoints/last.ckpt", map_location=torch.device("cpu")); print(json.dumps(m["loops"]["fit_loop"]["epoch_loop.batch_progress"], indent=2))'
```
Which will yield something like the following.  You want to look …

Resume at the end of the last trained epoch

---

everyvoice/wizard/__init__.py
everyvoice/wizard/basic.py
everyvoice/wizard/dataset.py

Support `~` and `~username` in wizard. This is particularly important because questionary.path allows using tilde, but then our code didn't expand it so an anto-completed path would not work in the end.
Fixes #539
approval
high - milestone a4
yes
I had not, but this question make me go back and add them... 😄 
run the wizard and use ~ or ~username in path-related questions
high
no
no

fix: resolve tilde in paths in wizard

---

everyvoice/preprocessor/preprocessor.py
everyvoice/tests/test_configs.py
everyvoice/tests/test_utils.py
everyvoice/tests/test_wizard.py
everyvoice/wizard/__init__.py
everyvoice/wizard/basic.py

I made these changes while working on the wizard's back and resume functions, but I want to PR them separately because they will be confusing to review as part of that PR.
- remove irrelevant unit-testing code from the Step class
- make more test suites compatible with Windows
- don't let the wizard leave directories around just to test that we're able to create them
- turn the warning about not running the sox effects on Windows into a fatal error, unless an explicit environment variable is set: we never want this warning to be ignorable!
sanity check
medium: these changes will be required for the wizard improvement PR
yes
- Should you really care to do so (but don't!), run the test suites on Windows, and see fewer failures.
- Tell the wizard to save files in a deep directory that …

A bunch of small improvements while working on the wizard back and resume

---

.github/workflows/test.yml
everyvoice/cli.py

allow synthesis with only the generator checkpoint
fixes https://github.com/EveryVoiceTTS/EveryVoice/issues/424
This PR allows users to "export" vocoder models (`everyvoice export`) which trims down the model by removing the discriminators. It also allows loading the vocoder model and inference/synthesis (not training) using only the generator. This allows us to distribute 50MB files instead of 950MB files when all people want to do is synthesize (not fine-tune/resume training)
https://github.com/EveryVoiceTTS/EveryVoice/issues/424
sanitty
high - alpha 4
Again, we do not have tests for inference unfortunately
take an existing vocoder and run `everyvoice export <path_to_vocoder.ckpt>` then try synthesizing using the generated `exported.ckpt` checkpoint.
medium-high
yes, alpha 4 …

allow synthesis with only the generator. add everyvoice export

---

everyvoice/preprocessor/preprocessor.py
everyvoice/tests/test_wizard.py

Reduce the confusion from the two nearly identical reports printed during `everyvoice preprocess`.
Fixes #342
beta
already covered by existing tests
Run `everyvoice preprocess config/everyvoice-text-to-spec.yaml` and see:
- The first report is labelled partial, and omits missing symbols, skipped processes, and nans, which are not related to audio-processing.
- The second report is like before, with this elements included.
medium-high
The `nans` line in the report is never actually populated. What's it supposed to count? should `_interpolate()` or `extract_pitch()` update it?

fix: display less confusing reports in preprocessing

---

everyvoice/cli.py
everyvoice/demo/app.py
everyvoice/tests/test_text.py

fixes #485
Allow basic allowlist/denylist functionality in demo. If an allowlist is supplied, then only those words/utterances are allowed to be synthesized. If a denylist is supplied, then only words/utterances not on the denylist are allowed to be synthesized. The former is more secure since it is more restricted. The latter can be hacked (I've done Unicode normalization to prevent Unicode homograph attacks, but there are a lot of other possible attacks, probably beyond scope of this PR).
#485
Sanity. Any improvements to make this more secure would be appreciated; there are a lot of hacks to get around the denylist at least. Some ideas may be able to be incorporated into this PR if they're easy enough, otherwise we can create issues.
0.1.0a5
No tests available for the demo.
create a …

add allowlist and denylist options to demo

---

everyvoice/tests/test_preprocessing.py
everyvoice/tests/test_wizard.py

Fixes #89
Unit test our glob code to make sure it works with deep symlink structures.
Fixed #89
rubber stamping
beta
nothing but!
If you change `WavsDirStep.validate()` to use `contains_wavs = next(path_expanded.glob("**/*.wav"), False)` instead of the current code, you'll see that `test_wizard` will fail on this new test function, but it passes with the current code.
```sh
python -m unittest \
everyvoice.tests.test_preprocessing.PreprocessingTest.test_no_speaker \
everyvoice.tests.test_wizard.WizardTest.test_wavs_dir
```
high
no
none

test: exercise finding wavs in nested symlink structures

---

.flake8
pyproject.toml

Refs:
- https://github.com/PyCQA/flake8/issues/234
- https://flake8.pycqa.org/en/latest/user/configuration.html
The flake8 configuration done in `pyproject.toml` is ineffective, because flake8 just does not support that, so all the previously ignored warnings and the rest of our configuration are suddenly ignored.
This PR restores our previous flake8 config.
testing I guess
question: do we want this in `.flake8` or in `setup.cfg`? I didn't use the latter because it would be the only tool we configure in there.
Before merging #582 I guess, so CI can pass for that PR.
n/a
Running `pre-commit run --all` should show no warnings from flake8. It will show lots of issues from black (#582 will fix that) and mypy, please ignore those for the purpose of this PR which only touches flake8.
high

fix: reconfigure flake8; it does not support pyproject.toml

---

.github/workflows/test.yml
everyvoice/run_tests.py

See https://github.com/EveryVoiceTTS/wav2vec2aligner/pull/14
Plus activate its testing in the main Everyvoice unit testing.
Fixes #326
And more

Several improvements to wav2vec2aligner system: early errors, testing, py 3.8 compatibility, etc

---

.github/workflows/publish.yaml
pyproject.toml

Turns out that our understanding of `pyproject.toml` with `hatch` was insufficient.
This PR aims to reduce what is included in a `sdist` and `whl`.
We decided to remove all `tests/` because they would require us to include the wav files and more which bloats the `whl` and `sdist`.
fixes: #586 
This PR as a long and explicit list of inclusions and exclusions, is this the best way of doing what we want to achieve?
Needed before our next release
None
Get yourself some reference prebuild `whl` and `sdist` files.
```sh
wget 'https://files.pythonhosted.org/packages/1c/c4/99440963fb2562fcf019d8949400c7467a6c10a524515e81f054cbbcb32a/everyvoice-0.1.0a3-py3-none-any.whl'
wget 'https://files.pythonhosted.org/packages/14/a4/898c980f6ee34ce240efb9f6d3ffbf24ed755497dc52751953ca5a2228e4/everyvoice-0.1.0a …
```

Making minimal sized `sdist` and `whl` using pyproject.toml

---

everyvoice/cli.py

When you run `everyvoice export` the vocoder HiFiGAN is exported as a HiFiGANGenerator which then breaks the model name validation. 
I just fixed the bug before creating an issue report since I just noticed it this weekend.
@SamuelLarkin - I'm not sure if the quick fix I've done here is the best way of addressing this, can you please advise if there is another place I should address the fix?
high - currently demos are broken with exported vocoders
I can't really test the exporting of a model because of the size of the vocoder model (1GB)
https://github.com/EveryVoiceTTS/HiFiGAN_iSTFT_lightning/pull/42

fix: exported model name should match generator class name

---

.github/workflows/test.yml

We don't actually need conda, at least not anymore:
- sox and ffmpeg can be installed with apt-get
- previously optimized pip installs for pyworld and pycountry can simply be cached by the standard pip caching mechanism, instead of using custom optimizations
The result is a more standard CI workflow, and a tiny bit faster to boot.
Mostly rubber stamping
normal
it's just CI
look at CI workflows from this branch vs others
high
no
none

ci: simplify CI EV install, use apt-get, remove conda

---

make-everyvoice-env

Fix make-everyvoice-env, which is currently broken
The fact that `pip install .[dev]` effectively undoes the editable installation we do one line up in `make-everyvoice-env`.
rubber stamping, it's already tested
high
no
This fails on `origin/main` right now, passes on this branch:
```
./make-everyvoice-env -n test-env
conda activate test-env
everyvoice/run_tests.py
```
high
no
none

fix(build): the last ev install in make-env has to be editable

---

README.md

On PyPI, like on GH, the quickstart instructions start with checking out EV from GitHub. We should start with PyPI-compatible instructions, then move on to instructions to install from source.
Make sure my updated instructions are correct
medium
no, but I tested these instructions while writing #600
Follow the new instructions and make sure the result is a valid environment.
high
no
no

docs: quickstart instructions for install from PyPI

---

everyvoice/cli.py
everyvoice/run_tests.py
everyvoice/tests/preprocessed_audio_fixture.py
everyvoice/tests/stubs.py
everyvoice/tests/test_cli.py
everyvoice/tests/test_configs.py
everyvoice/tests/test_dataloader.py
everyvoice/tests/test_doctests.py
everyvoice/tests/test_model.py
everyvoice/tests/test_preprocessing.py
everyvoice/tests/test_text.py
everyvoice/tests/test_utils.py
everyvoice/tests/test_wizard.py

Reduce the amount of output generated by our test suites.
Also fixed an issue where some of our doctest tests were not actually picked up.
general validation
medium
it's all about testing
Try `everyvoice/run_tests.py` with and without `-q` and enjoy how much less output there is on screen now.
high
no
~~none at the moment (there may be one for fs2 eventually, it's still pretty verbose)~~
https://github.com/EveryVoiceTTS/FastSpeech2_lightning/pull/99

Make test suites quiet(er)

---

everyvoice/tests/test_configs.py
pyproject.toml

See https://github.com/EveryVoiceTTS/FastSpeech2_lightning/pull/102
Also related: https://github.com/ReadAlongs/Studio/pull/253
Fixes #439 
This PR fetches readalong from github, because it depends on an unmerged and unpublished feature there.
This will get cleaned up in the merging process, so please review and test as is anyway.

Add .readalong format output to synthesize

---

.github/workflows/test.yml

Same as Studio and g2p, but with more exceptions whose licenses are not auto-detected.

ci: run licensecheck to auto-audit our dependencies

---

.github/workflows/docs.yml
.github/workflows/publish.yaml

Deploy docs CI workflow was broken: see https://github.com/EveryVoiceTTS/EveryVoice/actions/runs/12655263006 which failed on the last push to main.
We updated all our other workflow to use setup-python instead of conda incubator, this PR does the same for the deploy docs workflows.
Broken docs deploy
sanity checking
before the next PR merge to main, ideally
https://github.com/EveryVoiceTTS/EveryVoice/actions/runs/12656113424 ran with the docs deploy workflow, but with `--push` removed so it didn't push, and it completed successfully.
high
no
no

Dev.ej/fix docs ci

---

pyproject.toml
requirements.torch.txt

After some good testing by Marc, we can see that the audio quality is comparable with 2.3 and 2.1.
Torch 2.1.0 has vulnerabilities and is no longer available in some environments, so we decided to bump to 2.3.1.
At the EV dev meeting, we decided not to move to 2.4 yet as there is a Future Proofing warning we need to handle first (see #621).
Replaces #521, done in pyproject.toml instead of requirements.txt.
Fixes https://github.com/EveryVoiceTTS/EveryVoice/security/dependabot/2
Fixes https://github.com/EveryVoiceTTS/EveryVoice/security/dependabot/4
Fixes https://github.com/EveryVoiceTTS/EveryVoice/security/dependabot/10
Fixes https://github.com/EveryVoiceTTS/EveryVoice/security/dependabot/11
Fixes #558
high
tested manually
make a fresh env and run stuff
high, since we agreed to this at …

fix: move torch forward to 2.3.1

---

.github/workflows/docs.yml
.github/workflows/publish.yaml
.github/workflows/test.yml

Right now, every time we merge a PR to main, the docs get a updated and a commit get pushed to gh-pages. However, most of those comments are not contentful, except for updating that last modified date, which is misleading since the docs was not actually updated.
This PR only pushes the change to gh-pages if they're contentful.
Side change: now that our repos are public, we no longer need to use the SGILE_PAT in the workflows. (And I had to remove them to test this in my fork.)
sanity checking
low
tested in my fork, see 
- run with no changes: https://github.com/joanise/EveryVoice/actions/runs/12837570859/job/35801524637
- run with changes: https://github.com/joanise/EveryVoice/actions/runs/12837530499/job/35801398384
Make your own forks of the 5 repos, create commits that change the docs …

Dev.ej/update docs only on change

---

.github/workflows/test.yml
README.md
everyvoice/tests/regression/.gitignore
everyvoice/tests/regression/README.md
everyvoice/tests/regression/combine-coverage.sh
everyvoice/tests/regression/go.sh
everyvoice/tests/regression/prep-datasets.sh
everyvoice/tests/regression/regression-test.sh
everyvoice/tests/regression/wizard-resume-lj
everyvoice/tests/regression/wizard-resume-si
everyvoice/tests/regression/wizard-resume-xh
everyvoice/tests/test_cli.py
pyproject.toml

Starting to address #611
Start to write a regression test suite that we can sbatch submit to the cluster with GPUs and whatever memory we need.
For now, I'm using a tiny dataset, but it's easy to adjust to something larger.
While this is early, you can already try to give it a spin: edit the two user config variables at the top if needed, and run 
sbatch EveryVoice/everyvoice/tests/regression-test.sh
beta I guess
nothing but
medium, this still needs more work
no
no

feat: write a regression test suite that can be sbatch submitted

---

.github/workflows/test.yml
everyvoice/wizard/utils.py
pyproject.toml

Add support for Python 3.12 in EveryVoice
UserDict added its own implementation of `get()` in Python 3.12 (see https://github.com/python/cpython/pull/17910/files) and that broke our EnumDict. Fixed by adding our implementation of `get()` in EnumDict too.
sanity 
low
~I'm going to add matrix testing, to test this.~
Added matrix testing to exercise all the supported Python versions: 3.10 is the main test workflow, and 3.11 and 3.12 in the matrix one, with just unit testing.
make a new env with Python 3.12 and play around.
high
no
none

feat: add support for Python 3.12

---

.github/workflows/test.yml
.pre-commit-config.yaml
everyvoice/tests/test_wizard.py
everyvoice/wizard/tour.py
pyproject.toml

The warning about the resume file coming from a different version is too generic. We know 0.2.0 and 0.3.0 resume files are compatible, so adjust the warning to pay attention the which versions are compatible and not.
Are the two new messages clearer, and less likely to cause confusion?
beta
yes
Take an existing save wizard progress file, and edit line 2 to show version 0.3.0 (current), 0.2.0 (older and still compatible) or 0.1.0 (older, not compatible) and see no message, still compat message, or not compat message, respectively.
medium
no
none

feat: adjust the wizard resume message for known compatibility

---

everyvoice/cli.py
everyvoice/tests/test_cli.py

We moved to `uv` in #643 thus I created a `conda` free shell which fails with `everyvoice --diagnostic`.
#643 
Code review
low
No
```sh
everyvoice --diagnostic
```
or
```sh
python -m unittest everyvoice.tests.test_cli.CLITest.test_diagnostic
```
fair
No
None

Fix `--diagnostic` to work with `uv`

---

README.md
docs/install.md
make-everyvoice-env

We're still building EV envs with Python 3.10 by default, but I don't see any good reasons for that. This PR bumps the default to 3.12.
While it's a tiny change in the code, I want this to have its own PR so merging it (or not) is a deliberate decision.
Your vote on whether you think this bump is a good idea or not.
low
CI matrix testing already exercises 3.12, so this is already exercised.
You could build a new env with py 3.12 and make sure EV works.
high
no
none

feat: bump the default Python version to 3.12 in make-everyvoice-env

---

README.md
docs/install.md
mkdocs.yml

My earlier attempt at providing uv installation instructions were quite confusing. This PR cleans that up significantly, using a tabbed view where you can click "Using conda" or "Using uv" once, and all the instructions shown are toggled to your chosen package manager.
I also make the uv prerequisites clearer.
confusing instructions
How are the new instructions? Are they clear? Can I make them better?
low
n/a
https://joanise.github.io/EveryVoice/dev/install/
high - these are certainly much better than before
but medium - they can surely still be improved
no
no

Clarify the installation instructions conda vs uv via tabbed views

---

everyvoice/cli.py
everyvoice/demo/app.py
everyvoice/preprocessor/preprocessor.py
everyvoice/tests/test_preprocessing.py

This PR implements an idea for tracking down and removing problematic samples. By scoring individual utterances using the loss from a pre-trained model we can identify outliers and check for transcription errors or other issues. 
Documentation improvements, UX improvements, clarity etc..
normal
`everyvoice check-data -h` should tell you everything you need to know.
OK - I did this work quite a few months ago and then never followed up on it, so I've just finished it off and rebased everything. It appears to be working as expected but some extra eyes would be appreciated.
no version change necessary
https://github.com/EveryVoiceTTS/FastSpeech2_lightning/pull/101

chore: update submodule to include scorer

---

everyvoice/tests/g2p_engines/__init__.py
everyvoice/tests/stubs.py
everyvoice/tests/test_wizard.py
everyvoice/utils/__init__.py
everyvoice/wizard/__init__.py
everyvoice/wizard/basic.py
everyvoice/wizard/dataset.py
everyvoice/wizard/tour.py
everyvoice/wizard/utils.py

This is my second big PR related to custom g2p in the wizard: this one adds the questions and handles it all, plus testing.
Known bug: if you have a given lang that is used in more than one dataset in the same project, and you set the custom g2p on any other than the first where that language occurs, the earlier datasets won't have been processed with the custom g2p.
I am deferring fixing this issue to its own PR as it entails another significant round of refactoring that I want to do later and have reviewed separately.
Fixing that bug should require no user-visible changes, so the wizard enhancements can be tested and reviewed before that gets fixed.
- fixing the bug described above -- ticket created: #712
- documentation, that's for #354 
- I might want to handle an old resume files …

Dev.ej/custom g2p wiz

---

everyvoice/tests/stubs.py
everyvoice/tests/test_custom_g2p.py
everyvoice/tests/test_wizard.py
everyvoice/wizard/basic.py
everyvoice/wizard/dataset.py
everyvoice/wizard/prompts.py

Use `questionary.text(xyz).ask` instead of overrided `input(xyz)`. This allows use of left and right arrow keys when running the EV wizard.
Fixes #574
Have I refactored the tests properly? `patch_input` was frequently replaced with `patch_questionary`
Tests were simply refactored. No new functionality
Run the EveryVoice wizard!
patch

fix: use questionary.text in Wizard

---

everyvoice/base_cli/checkpoint.py
everyvoice/cli.py
everyvoice/tests/test_cli.py

Use `typer.BadParameter` when it's a clear user CLI error, not a programming error: this gives a more concise error message.
Update the wav2vec2aligner submodule to incorporate https://github.com/EveryVoiceTTS/wav2vec2aligner/pull/24
Replaces long stack traces by short messages to the point when you run `everyvoice checkpoint rename-speaker` but specify a speaker who does not exist or the model has no speakers.
sanity checking
low 
no
run `everyvoice checkpoint rename-speaker` with a model that does not have a speaker, and one where the speaker you provide does not exist in the model.
high
no
https://github.com/EveryVoiceTTS/wav2vec2aligner/pull/24

Dev.ej/misc fixes

---

.github/workflows/docs.yml
.github/workflows/matrix-tests.yml
.github/workflows/publish.yaml
.github/workflows/test.yml
everyvoice/tests/test_cli.py

We previously matrix tested three Python versions with Ubuntu, but not with MacOS. Since Macs are a pretty common EveryVoice use case, it makes sense to test it too in CI.
While I'm here, some small additional tweaks:
- allow 30 minutes per run, because somethings our 15 minute limit is too short
- bump actions/checkout to the latest version, @v5
- Use FedericoCarboni/setup-ffmpeg@v2 instead of apt-get to install ffmpeg, because the former take 2s while the latter takes much longer. We don't need the latest ffmpeg, so there's no value in doing it the slower way.
For MacOS, I'm using conda because I could not figure out how to install sox in CI any other way. If someone can figure out a more direct sox installation path, great, but otherwise this is fine as is.
low
nothing but
look at the …

Add MacOS to matrix testing
